

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ====================
-- Schema metadata
-- ====================

COMMENT ON SCHEMA "public" IS 'standard public schema';

-- ====================
-- Extensions
-- ====================

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

-- ====================
-- Functions
-- ====================

CREATE OR REPLACE FUNCTION "public"."current_user_id"() RETURNS bigint
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT id FROM public.users WHERE auth_id = auth.uid() LIMIT 1;
$$;

ALTER FUNCTION "public"."current_user_id"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."leaderboard_top_100"() RETURNS TABLE("rank" bigint, "user_id" bigint, "total_point" integer, "solved_count" bigint, "display_name" character varying, "email" character varying)
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  WITH scores AS (
    SELECT
      pl.user_id,
      MAX(pl.total_point)::int AS total_point,
      COUNT(DISTINCT pl.question_id)::bigint AS solved_count
    FROM public.point_logs pl
    GROUP BY pl.user_id
  ),
  ranked AS (
    SELECT
      ROW_NUMBER() OVER (ORDER BY s.total_point DESC, s.user_id ASC)::bigint AS rank,
      s.user_id,
      s.total_point,
      s.solved_count
    FROM scores s
  )
  SELECT
    r.rank,
    r.user_id,
    r.total_point,
    r.solved_count,
    u.display_name,
    u.email
  FROM ranked r
  INNER JOIN public.users u ON u.id = r.user_id
  WHERE r.rank <= 100;
$$;

ALTER FUNCTION "public"."leaderboard_top_100"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

-- ====================
-- Tables
-- ====================

CREATE TABLE IF NOT EXISTS "public"."ai_feedback" (
    "id" bigint NOT NULL,
    "submission_id" bigint NOT NULL,
    "feedback_type" character varying(30),
    "feedback_content" "text",
    "created_at" timestamp with timeone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."ai_feedback" OWNER TO "postgres";

ALTER TABLE "public"."ai_feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ai_feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."languages" (
    "id" smallint NOT NULL,
    "name" character varying(20),
    "compile_cmd" "text",
    "run_cmd" "text",
    "status" boolean DEFAULT true
);

ALTER TABLE "public"."languages" OWNER TO "postgres";

ALTER TABLE "public"."languages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."languages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."point_logs" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "submission_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "point" integer NOT NULL,
    "total_point" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."point_logs" OWNER TO "postgres";

ALTER TABLE "public"."point_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."point_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."question_categories" (
    "id" integer NOT NULL,
    "name" character varying(50) NOT NULL,
    "description" character varying(100),
    "status" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" bigint NOT NULL,
    "updated_at" timestamp with time zone,
    "updated_by" bigint
);

ALTER TABLE "public"."question_categories" OWNER TO "postgres";

ALTER TABLE "public"."question_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."question_tag" (
    "question_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);

ALTER TABLE "public"."question_tag" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" bigint NOT NULL,
    "code" character varying(16) NOT NULL,
    "category_id" integer NOT NULL,
    "title" character varying(50) NOT NULL,
    "description" "text",
    "constraints" "text",
    "solution" "text",
    "uri" "text" NOT NULL,
    "difficulty" smallint,
    "expected_complexity" character varying(20),
    "time_limit" integer,
    "memory_limit" integer,
    "status" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" bigint NOT NULL,
    "updated_at" timestamp with time zone,
    "updated_by" bigint,
    "points" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "questions_points_non_negative" CHECK (("points" >= 0))
);

ALTER TABLE "public"."questions" OWNER TO "postgres";

ALTER TABLE "public"."questions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."submission_test_cases" (
    "id" bigint NOT NULL,
    "submission_id" bigint,
    "test_case_id" bigint,
    "output_data" "text",
    "error_message" "text",
    "run_time" integer,
    "memory_used" integer,
    "status" smallint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."submission_test_cases" OWNER TO "postgres";

ALTER TABLE "public"."submission_test_cases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."submission_test_cases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."submissions" (
    "id" bigint NOT NULL,
    "pid" bigint DEFAULT 0,
    "user_id" bigint,
    "question_id" bigint,
    "answer" "text" NOT NULL,
    "compile_error" "text",
    "status" smallint,
    "run_time" integer,
    "memory_used" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "language" character varying(40) NOT NULL
);

ALTER TABLE "public"."submissions" OWNER TO "postgres";

ALTER TABLE "public"."submissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."submissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."system_settings" (
    "key" character varying(255) NOT NULL,
    "value" "jsonb" NOT NULL,
    "updated_by" bigint,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);

ALTER TABLE "public"."system_settings" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "name" character varying(50) NOT NULL,
    "status" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" bigint NOT NULL,
    "updated_at" timestamp with time zone,
    "updated_by" bigint
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."test_cases" (
    "id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "input_data" "text" NOT NULL,
    "output_data" "text" NOT NULL,
    "case_order" integer,
    "is_simple" boolean DEFAULT false,
    "status" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" bigint NOT NULL,
    "updated_at" timestamp with time zone,
    "updated_by" bigint
);

ALTER TABLE "public"."test_cases" OWNER TO "postgres";

ALTER TABLE "public"."test_cases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_cases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "display_name" character varying(255),
    "role_id" smallint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "email" character varying(255),
    "password_hash" character varying(255),
    "avatar_url" "text",
    "bio" "text",
    "phone" character varying(50),
    "dob" date
);

ALTER TABLE "public"."users" OWNER TO "postgres";

ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ====================
-- Constraints (primary keys / uniques)
-- ====================

ALTER TABLE ONLY "public"."ai_feedback"
    ADD CONSTRAINT "ai_feedback_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."languages"
    ADD CONSTRAINT "languages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."point_logs"
    ADD CONSTRAINT "point_logs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."question_categories"
    ADD CONSTRAINT "question_categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_pkey" PRIMARY KEY ("question_id", "tag_id");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."submission_test_cases"
    ADD CONSTRAINT "submission_test_cases_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."system_settings"
    ADD CONSTRAINT "system_settings_pkey" PRIMARY KEY ("key");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ====================
-- Indexes
-- ====================

CREATE INDEX "idx_ai_feedback_submission_id" ON "public"."ai_feedback" USING "btree" ("submission_id");

CREATE INDEX "idx_point_logs_question_id" ON "public"."point_logs" USING "btree" ("question_id");

CREATE INDEX "idx_point_logs_user_id" ON "public"."point_logs" USING "btree" ("user_id");

CREATE INDEX "idx_question_tag_question_id" ON "public"."question_tag" USING "btree" ("question_id");

CREATE INDEX "idx_question_tag_tag_id" ON "public"."question_tag" USING "btree" ("tag_id");

CREATE INDEX "idx_questions_category_id" ON "public"."questions" USING "btree" ("category_id");

CREATE INDEX "idx_questions_created_by" ON "public"."questions" USING "btree" ("created_by");

CREATE INDEX "idx_submission_test_cases_submission_id" ON "public"."submission_test_cases" USING "btree" ("submission_id");

CREATE INDEX "idx_submissions_question_id" ON "public"."submissions" USING "btree" ("question_id");

CREATE INDEX "idx_submissions_user_id" ON "public"."submissions" USING "btree" ("user_id");

CREATE INDEX "idx_test_cases_question_id" ON "public"."test_cases" USING "btree" ("question_id");

CREATE UNIQUE INDEX "idx_users_email" ON "public"."users" USING "btree" ("email") WHERE ("email" IS NOT NULL);

CREATE UNIQUE INDEX "uq_point_logs_user_question" ON "public"."point_logs" USING "btree" ("user_id", "question_id");

-- ====================
-- Foreign keys
-- ====================

ALTER TABLE ONLY "public"."ai_feedback"
    ADD CONSTRAINT "ai_feedback_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."point_logs"
    ADD CONSTRAINT "point_logs_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."point_logs"
    ADD CONSTRAINT "point_logs_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."point_logs"
    ADD CONSTRAINT "point_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."question_categories"
    ADD CONSTRAINT "question_categories_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."question_categories"
    ADD CONSTRAINT "question_categories_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."question_categories"("id");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."submission_test_cases"
    ADD CONSTRAINT "submission_test_cases_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."submission_test_cases"
    ADD CONSTRAINT "submission_test_cases_test_case_id_fkey" FOREIGN KEY ("test_case_id") REFERENCES "public"."test_cases"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id");

ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."system_settings"
    ADD CONSTRAINT "system_settings_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id");

ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."test_cases"
    ADD CONSTRAINT "test_cases_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id");

-- ====================
-- Row level security (RLS) + policies
-- ====================

ALTER TABLE "public"."ai_feedback" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ai_feedback_insert" ON "public"."ai_feedback" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "ai_feedback_select" ON "public"."ai_feedback" FOR SELECT TO "authenticated" USING (true);

ALTER TABLE "public"."languages" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "languages_select_authenticated" ON "public"."languages" FOR SELECT TO "authenticated" USING (true);

ALTER TABLE "public"."point_logs" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."question_categories" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "question_categories_delete" ON "public"."question_categories" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "question_categories_insert" ON "public"."question_categories" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "question_categories_select" ON "public"."question_categories" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "question_categories_update" ON "public"."question_categories" FOR UPDATE TO "authenticated" USING (true);

ALTER TABLE "public"."question_tag" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "question_tag_delete" ON "public"."question_tag" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "question_tag_insert" ON "public"."question_tag" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "question_tag_select" ON "public"."question_tag" FOR SELECT TO "authenticated" USING (true);

ALTER TABLE "public"."questions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "questions_delete" ON "public"."questions" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "questions_insert" ON "public"."questions" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "questions_select" ON "public"."questions" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "questions_update" ON "public"."questions" FOR UPDATE TO "authenticated" USING (true);

ALTER TABLE "public"."submission_test_cases" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "submission_test_cases_select" ON "public"."submission_test_cases" FOR SELECT TO "authenticated" USING (true);

ALTER TABLE "public"."submissions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "submissions_insert_own" ON "public"."submissions" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "public"."current_user_id"()));

CREATE POLICY "submissions_select_own" ON "public"."submissions" FOR SELECT TO "authenticated" USING (("user_id" = "public"."current_user_id"()));

ALTER TABLE "public"."system_settings" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tags_delete" ON "public"."tags" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "tags_insert" ON "public"."tags" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "tags_select" ON "public"."tags" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "tags_update" ON "public"."tags" FOR UPDATE TO "authenticated" USING (true);

ALTER TABLE "public"."test_cases" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "test_cases_delete" ON "public"."test_cases" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "test_cases_insert" ON "public"."test_cases" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "test_cases_select" ON "public"."test_cases" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "test_cases_update" ON "public"."test_cases" FOR UPDATE TO "authenticated" USING (true);

ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

-- ====================
-- Publication ownership
-- ====================
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

-- ====================
-- Grants
-- ====================
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."current_user_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."current_user_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_user_id"() TO "service_role";

GRANT ALL ON FUNCTION "public"."leaderboard_top_100"() TO "anon";
GRANT ALL ON FUNCTION "public"."leaderboard_top_100"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."leaderboard_top_100"() TO "service_role";

GRANT ALL ON TABLE "public"."ai_feedback" TO "anon";
GRANT ALL ON TABLE "public"."ai_feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_feedback" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ai_feedback_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ai_feedback_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ai_feedback_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."languages" TO "anon";
GRANT ALL ON TABLE "public"."languages" TO "authenticated";
GRANT ALL ON TABLE "public"."languages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."languages_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."point_logs" TO "anon";
GRANT ALL ON TABLE "public"."point_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."point_logs" TO "service_role";

GRANT ALL ON SEQUENCE "public"."point_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."point_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."point_logs_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."question_categories" TO "anon";
GRANT ALL ON TABLE "public"."question_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."question_categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."question_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."question_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."question_categories_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."question_tag" TO "anon";
GRANT ALL ON TABLE "public"."question_tag" TO "authenticated";
GRANT ALL ON TABLE "public"."question_tag" TO "service_role";

GRANT ALL ON TABLE "public"."questions" TO "anon";
GRANT ALL ON TABLE "public"."questions" TO "authenticated";
GRANT ALL ON TABLE "public"."questions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."submission_test_cases" TO "anon";
GRANT ALL ON TABLE "public"."submission_test_cases" TO "authenticated";
GRANT ALL ON TABLE "public"."submission_test_cases" TO "service_role";

GRANT ALL ON SEQUENCE "public"."submission_test_cases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."submission_test_cases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."submission_test_cases_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."submissions" TO "anon";
GRANT ALL ON TABLE "public"."submissions" TO "authenticated";
GRANT ALL ON TABLE "public"."submissions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."submissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."submissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."submissions_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."system_settings" TO "anon";
GRANT ALL ON TABLE "public"."system_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."system_settings" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."test_cases" TO "anon";
GRANT ALL ON TABLE "public"."test_cases" TO "authenticated";
GRANT ALL ON TABLE "public"."test_cases" TO "service_role";

GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_cases_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";

-- ====================
-- Default privileges
-- ====================
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";

-- ====================
-- Migrations / Schema Updates
-- ====================

-- Ensure profile fields exist for existing users
ALTER TABLE IF EXISTS "public"."users" ADD COLUMN IF NOT EXISTS "bio" "text";
ALTER TABLE IF EXISTS "public"."users" ADD COLUMN IF NOT EXISTS "phone" character varying(50);
ALTER TABLE IF EXISTS "public"."users" ADD COLUMN IF NOT EXISTS "dob" date;
