-- ==========================================
-- UPDATE SCHEMA: PROGRESSION SYSTEMS & LEADERBOARD
-- Date: 2026-04-22
-- ==========================================

-- 1. User Streaks
CREATE TABLE IF NOT EXISTS "public"."user_streaks" (
    "user_id" bigint PRIMARY KEY REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "current_streak" integer DEFAULT 0 NOT NULL,
    "max_streak" integer DEFAULT 0 NOT NULL,
    "last_activity_date" date,
    "activity_history" boolean[] DEFAULT ARRAY[]::boolean[]
);

-- 2. Achievements Master Table
CREATE TABLE IF NOT EXISTS "public"."achievements" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(100) UNIQUE NOT NULL, -- Added UNIQUE to prevent ghosting/duplicates
    "description" text,
    "icon" character varying(50),
    "criteria_type" character varying(50), -- e.g., 'solve_count', 'streak_count', 'language_count'
    "criteria_value" integer,
    "color" character varying(50),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Cleanup duplicates if any (in case UNIQUE wasn't there before)
DELETE FROM "public"."achievements" a
USING "public"."achievements" b
WHERE a.id > b.id AND a.name = b.name;

-- 3. User Achievements (Earned Badges)
CREATE TABLE IF NOT EXISTS "public"."user_achievements" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "achievement_id" bigint REFERENCES "public"."achievements"("id") ON DELETE CASCADE,
    "earned_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE("user_id", "achievement_id")
);

-- 4. User Skill Mastery
CREATE TABLE IF NOT EXISTS "public"."user_skills" (
    "user_id" bigint PRIMARY KEY REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "frontend" integer DEFAULT 0 NOT NULL,
    "backend" integer DEFAULT 0 NOT NULL,
    "algorithms" integer DEFAULT 0 NOT NULL,
    "devops" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. Achievements Master Table (Updated with Metadata)
ALTER TABLE IF EXISTS "public"."achievements" ADD COLUMN IF NOT EXISTS "created_by" bigint REFERENCES "public"."users"("id");
ALTER TABLE IF EXISTS "public"."achievements" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone;
ALTER TABLE IF EXISTS "public"."achievements" ADD COLUMN IF NOT EXISTS "updated_by" bigint REFERENCES "public"."users"("id");

-- 5. Audit Logs (System Activity)
CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint REFERENCES "public"."users"("id") ON DELETE SET NULL,
    "action_type" character varying(100) NOT NULL, -- 'SYSTEM_CONFIG', 'SUBMISSION', 'OLLAMA_REQ', 'PISTON_REQ'
    "action_details" jsonb DEFAULT '{}'::jsonb,
    "ip_address" character varying(45),
    "user_agent" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS for audit_logs
ALTER TABLE "public"."audit_logs" ENABLE ROW LEVEL SECURITY;

-- Policies for audit_logs (Only admins can see logs)
DROP POLICY IF EXISTS "audit_logs_select_admin" ON "public"."audit_logs";
CREATE POLICY "audit_logs_select_admin" ON "public"."audit_logs" 
FOR SELECT TO "authenticated" 
USING (true);

-- Policies
DROP POLICY IF EXISTS "user_streaks_select" ON "public"."user_streaks";
CREATE POLICY "user_streaks_select" ON "public"."user_streaks" FOR SELECT TO "authenticated" USING (true);

DROP POLICY IF EXISTS "achievements_select" ON "public"."achievements";
CREATE POLICY "achievements_select" ON "public"."achievements" FOR SELECT TO "authenticated" USING (true);

DROP POLICY IF EXISTS "user_achievements_select" ON "public"."user_achievements";
CREATE POLICY "user_achievements_select" ON "public"."user_achievements" FOR SELECT TO "authenticated" USING (true);

DROP POLICY IF EXISTS "user_skills_select" ON "public"."user_skills";
CREATE POLICY "user_skills_select" ON "public"."user_skills" FOR SELECT TO "authenticated" USING (true);

-- Initial Achievements Seed
INSERT INTO "public"."achievements" ("name", "description", "icon", "criteria_type", "criteria_value", "color") VALUES
('First Blood', 'Solve your first problem', 'zap', 'solve_count', 1, 'text-amber-400'),
('Night Owl', 'Solve a problem between 12 AM - 5 AM', 'clock', 'night_solve', 1, 'text-purple-400'),
('Consistency', 'Maintain a 7-day streak', 'fire', 'streak_count', 7, 'text-orange-500'),
('Polyglot', 'Solve problems in 3 different languages', 'codearea-logo', 'language_count', 3, 'text-blue-400'),
('Algorithm Master', 'Complete 50 algorithm problems', 'cpu', 'category_solve_count', 50, 'text-emerald-500')
ON CONFLICT DO NOTHING;

-- Update leaderboard_top_100 to include avatar_url
DROP FUNCTION IF EXISTS "public"."leaderboard_top_100"();
CREATE OR REPLACE FUNCTION "public"."leaderboard_top_100"() 
RETURNS TABLE("rank" bigint, "user_id" bigint, "total_point" integer, "solved_count" bigint, "display_name" character varying, "email" character varying, "avatar_url" text)
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  WITH scores AS (
    SELECT
      pl.user_id,
      MAX(pl.total_point)::int AS total_point,
      COUNT(DISTINCT pl.question_id)::bigint AS solved_count
    FROM public.point_logs pl
    GROUP BY pl.user_id
  ),
  ranked AS (
    SELECT
      ROW_NUMBER() OVER (ORDER BY s.total_point DESC, s.user_id ASC)::bigint AS rank,
      s.user_id,
      s.total_point,
      s.solved_count
    FROM scores s
  )
  SELECT
    r.rank,
    r.user_id,
    r.total_point,
    r.solved_count,
    u.display_name,
    u.email,
    u.avatar_url
  FROM ranked r
  INNER JOIN public.users u ON u.id = r.user_id
  WHERE r.rank <= 100;
$$;
