version: "3.7"

services:
  server:
    platform: linux/amd64
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    restart: always

  worker:
    platform: linux/amd64
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ./redis-data:/data
    restart: always
