# Judge0 Configuration File
#
# See the official Judge0 documentation for more information:
# https://docs.judge0.com/

# Database settings
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

# Redis settings
REDIS_HOST=redis
REDIS_PORT=6379

# Server settings
PORT=2358
ALLOW_CORS=true

# Worker settings
# (adjust based on your machine's resources)
CONCURRENCY=1
