-- CodeArea Back Office - Initial schema
-- users: id bigint, auth_id links to Supabase Auth (auth.users.id), no password in public.users

-- Users (auth_id = Supabase Auth user id for login/register)
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE NOT NULL,
  display_name varchar(255),
  role_id smallint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Question categories
CREATE TABLE public.question_categories (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(100),
  status boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint NOT NULL REFERENCES public.users(id),
  updated_at timestamptz,
  updated_by bigint REFERENCES public.users(id)
);

-- Tags
CREATE TABLE public.tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  status boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint NOT NULL REFERENCES public.users(id),
  updated_at timestamptz,
  updated_by bigint REFERENCES public.users(id)
);

-- Languages
CREATE TABLE public.languages (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20),
  compile_cmd text,
  run_cmd text,
  status boolean DEFAULT true
);

-- Questions
CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(16) NOT NULL,
  category_id int NOT NULL REFERENCES public.question_categories(id),
  title varchar(50) NOT NULL,
  description text,
  constraints text,
  solution text,
  uri varchar(50) NOT NULL,
  difficulty smallint,
  expected_complexity varchar(20),
  time_limit int,
  memory_limit int,
  status boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint NOT NULL REFERENCES public.users(id),
  updated_at timestamptz,
  updated_by bigint REFERENCES public.users(id)
);

-- Question <-> Tag (many-to-many)
CREATE TABLE public.question_tag (
  question_id bigint NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (question_id, tag_id)
);

-- Test cases
CREATE TABLE public.test_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  input_data text NOT NULL,
  output_data text NOT NULL,
  case_order int,
  is_simple boolean DEFAULT false,
  status boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint NOT NULL REFERENCES public.users(id),
  updated_at timestamptz,
  updated_by bigint REFERENCES public.users(id)
);

-- Submissions
CREATE TABLE public.submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pid int NOT NULL,
  user_id bigint REFERENCES public.users(id),
  question_id bigint REFERENCES public.questions(id),
  languages_id smallint NOT NULL REFERENCES public.languages(id),
  answer text NOT NULL,
  compile_error text,
  status smallint,
  run_time int,
  memory_used int,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Submission test case results
CREATE TABLE public.submission_test_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint REFERENCES public.submissions(id) ON DELETE CASCADE,
  test_case_id bigint REFERENCES public.test_cases(id) ON DELETE CASCADE,
  output_data text,
  error_message text,
  run_time int,
  memory_used int,
  status smallint,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- AI feedback for submissions
CREATE TABLE public.ai_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id bigint NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  feedback_type varchar(30),
  feedback_content text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for common lookups
CREATE INDEX idx_questions_category_id ON public.questions(category_id);
CREATE INDEX idx_questions_created_by ON public.questions(created_by);
CREATE INDEX idx_question_tag_question_id ON public.question_tag(question_id);
CREATE INDEX idx_question_tag_tag_id ON public.question_tag(tag_id);
CREATE INDEX idx_test_cases_question_id ON public.test_cases(question_id);
CREATE INDEX idx_submissions_user_id ON public.submissions(user_id);
CREATE INDEX idx_submissions_question_id ON public.submissions(question_id);
CREATE INDEX idx_submission_test_cases_submission_id ON public.submission_test_cases(submission_id);
CREATE INDEX idx_ai_feedback_submission_id ON public.ai_feedback(submission_id);
CREATE UNIQUE INDEX idx_users_auth_id ON public.users(auth_id);

-- Optional: enable RLS and add policies in a later migration
