-- Submissions: language as plain text (Piston language id) instead of FK to languages
-- Questions: points awarded on full hidden-test pass
-- point_logs: per solve reward + running cumulative total

ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS points int NOT NULL DEFAULT 0;

ALTER TABLE public.submissions DROP CONSTRAINT IF EXISTS submissions_languages_id_fkey;

ALTER TABLE public.submissions
  ADD COLUMN IF NOT EXISTS language varchar(40);

UPDATE public.submissions s
SET language = COALESCE(
  (SELECT l.name FROM public.languages l WHERE l.id = s.languages_id),
  'python'
)
WHERE s.language IS NULL;

ALTER TABLE public.submissions
  ALTER COLUMN language SET NOT NULL;

ALTER TABLE public.submissions DROP COLUMN IF EXISTS languages_id;

ALTER TABLE public.submissions
  ALTER COLUMN pid DROP NOT NULL,
  ALTER COLUMN pid SET DEFAULT 0;

UPDATE public.submissions SET pid = 0 WHERE pid IS NULL;

CREATE TABLE IF NOT EXISTS public.point_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  submission_id bigint NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  question_id bigint NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  point int NOT NULL,
  total_point int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_point_logs_user_id ON public.point_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_point_logs_question_id ON public.point_logs(question_id);

-- One scored solve per user per question (backend skips insert if already exists)
CREATE UNIQUE INDEX IF NOT EXISTS uq_point_logs_user_question ON public.point_logs(user_id, question_id);
