-- Tables for progression systems

-- 1. User Streaks
CREATE TABLE IF NOT EXISTS "public"."user_streaks" (
    "user_id" bigint PRIMARY KEY REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "current_streak" integer DEFAULT 0 NOT NULL,
    "max_streak" integer DEFAULT 0 NOT NULL,
    "last_activity_date" date,
    "activity_history" boolean[] DEFAULT ARRAY[]::boolean[]
);

-- 2. Achievements Master Table
CREATE TABLE IF NOT EXISTS "public"."achievements" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(100) NOT NULL,
    "description" text,
    "icon" character varying(50),
    "criteria_type" character varying(50), -- e.g., 'solve_count', 'streak_count', 'language_count'
    "criteria_value" integer,
    "color" character varying(50),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. User Achievements (Earned Badges)
CREATE TABLE IF NOT EXISTS "public"."user_achievements" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "achievement_id" bigint REFERENCES "public"."achievements"("id") ON DELETE CASCADE,
    "earned_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE("user_id", "achievement_id")
);

-- 4. User Skill Mastery
CREATE TABLE IF NOT EXISTS "public"."user_skills" (
    "user_id" bigint PRIMARY KEY REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "frontend" integer DEFAULT 0 NOT NULL,
    "backend" integer DEFAULT 0 NOT NULL,
    "algorithms" integer DEFAULT 0 NOT NULL,
    "devops" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE "public"."user_streaks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."achievements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_achievements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_skills" ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "user_streaks_select" ON "public"."user_streaks" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "achievements_select" ON "public"."achievements" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "user_achievements_select" ON "public"."user_achievements" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "user_skills_select" ON "public"."user_skills" FOR SELECT TO "authenticated" USING (true);

-- Initial Achievements Seed
INSERT INTO "public"."achievements" ("name", "description", "icon", "criteria_type", "criteria_value", "color") VALUES
('First Blood', 'Solve your first problem', 'zap', 'solve_count', 1, 'text-amber-400'),
('Night Owl', 'Solve a problem between 12 AM - 5 AM', 'clock', 'night_solve', 1, 'text-purple-400'),
('Consistency', 'Maintain a 7-day streak', 'fire', 'streak_count', 7, 'text-orange-500'),
('Polyglot', 'Solve problems in 3 different languages', 'codearea-logo', 'language_count', 3, 'text-blue-400'),
('Algorithm Master', 'Complete 50 algorithm problems', 'cpu', 'category_solve_count', 50, 'text-emerald-500');
